name: Auto tag based on commit msg
on:   
  push:
    branches: ['develop']

jobs:
  build:
    name: 'Bump version and commit package.json'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v3'
        with:
          token: ${{ secrets.BOT_USER_TOKEN }}
          ref: 'develop'

      - name:  'Automated Version Bump'
        id: version-bump
        uses:  'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_USER_TOKEN }}
        with:
          patch-wording: '[npm release]'
          tag-prefix:  'v'
          target-branch: 'develop'
  call-npm-publish-workflow:
    needs: build
    if: "startsWith(github.event.pull_request.title, '[npm release]')"
    uses: ./.github/workflows/npm-publish.yml
