
name: npm publish based on commit msg
on: 
  workflow_call:

jobs:
  build:
    name: 'npm publish'
    runs-on: ubuntu-latest
    # if: "startsWith(github.event.head_commit.message, '[npm release]')"
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: 'Checkout source code'
        uses: 'actions/checkout@v2'

      - name: 'Show current version'
        run: grep  '"version"' package.json

      # Setup .npmrc file to publish to npm
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          # Defaults to the user or organization that owns the workflow file
          scope: '@openbeta'

      - name: NPM publish
        run: yarn install --no-progress && yarn lint && yarn test && yarn build && yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
